### ISSUE TITLE
Unsatisfied Link Error when running the program

### ISSUE THREAD

**Issue by ashwinbhaskar** [infinyon/fluvio-client-java#72]
I am trying to run a basic `produce, consume` code using fluvio java library. It compiles fine. But when I run the program, it gives this stack trace
```
Exception in thread "sbt-bg-threads-1" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/66/8ybncfzx7lzdvsf_twjjg4yh0000gn/T/nativeutils439095764547250/libfluvio_java.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.infinyon.fluvio.NativeUtils.loadLibraryFromJar(NativeUtils.java:126)
	at com.infinyon.fluvio.Fluvio.<clinit>(Fluvio.java:93)
	at FluvioTest$.<clinit>(FluvioTest.scala:16)
	at FluvioTest.main(FluvioTest.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ashwinbhaskar** [comment]
I am running on MacOS Monterey with Apple M1 chip

**Comment by sehz** [comment]
Got it.  We have open issue regarding m1: https://github.com/infinyon/fluvio-client-java/issues/22
